### ISSUE TITLE
Fix up some minor changes w/ First Website

### ISSUE THREAD

**Issue by gregthompson27** [drewduvieilh/drewduvieilh.github.io#1]
<h3>Feedback for todo 7</h3>

https://github.com/drewduvieilh/drewduvieilh.github.io/blob/71363149823e2c33235e7735310bef64eb57c784/index.html#L29

@drewduvieilh, your `<img>` tag on line 29 is missing a closing `>` symbol at the end of the line. Go ahead and add that symbol there.

___ 

<h3>Feedback for all-contents div</h3>

https://github.com/drewduvieilh/drewduvieilh.github.io/blob/71363149823e2c33235e7735310bef64eb57c784/index.html#L10-L12

Next, your all-contents div that should have all other elements inside of it that starts on line 10 closes immediately on line 12. You can delete that closing `</div>` tag on line 12.

___

https://github.com/drewduvieilh/drewduvieilh.github.io/blob/71363149823e2c33235e7735310bef64eb57c784/index.html#L37

Looks like this opening tag inadvertently got a `/` before the `div` - opening tags don't need slashes so you can get rid of that.

Finally, the closing div tag that you have on what is currently line 47 is an extra closing tag that doesn't match up with any opening tag and should be removed.

**Comment by JoshHunter11** [comment]
@gregthompson27 All issues resolved
